print("haloo siapa nama kamu?")
nama = input("memasukan nama :")
print("dimana kamu tinggal?")
alamat = input("memasukan alamat :")
print("berapa umur kamu?")
umur = input("memasukan umur kamu")
print("dimana kamu lahir?")
tempat_lahir = input("memasukan tempat :")
print("senang bertemu denganmu", nama, "dari", alamat, "umur:", umur, "tempat lahir di:", tempat_lahir)
